spring:
  profiles: #使用的配置文件
    active: dev
  application:
    name: hot-load
  messages:
    basename: i18n/messages

#服务端口
server:
  port: 9090
  error:
    path: /custom/error


logging:
  level:
    root: info
    com.hot: debug

